### ISSUE TITLE
Combining gRPC(app) with MCA

### ISSUE THREAD

**Issue by sub2sub2** [sub2sub2/AI-LINUX-RUST#23]
So far, we have confirmed gRPC, MCA, and AI model working well respectively. Also, I checked that MCA and AI model are working well together. But as we know, gRPC and MCA have some problem(maybe thread safety issue).

If we have any update or get some progress, let's update on this issue page.

**Comment by sseoreo** [comment]
We've encountered a persistent challenge with the following error:

```
...
future created by async block is not `Send`

= help: within `{async block@src/services/iris.rs:15:122: 49:6}`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, ModelConnection>`
```
It seems the issue stems from accessing the struct ModelConnection, which is based on a singleton pattern.

When a thread accesses the ModelConnection struct (in our case, a thread corresponds to the gRPC function 'inference'), the struct must implement the traits Sync and Send. These traits ensure the safe transfer of the property to another thread.

Although you've already implemented these traits for ModelConnection, inexplicably, ModelConnection is referenced as the type MutexGuard<'_, ModelConnection>. Consequently, the error indicates that the Send trait is not implemented.

As a temporary workaround, I invoke Model1Struct instead of ModelConnection in the inference method like this:
```
async fn inference(
    sepal_length: f32, sepal_width: f32, petal_length: f32, petal_width: f32) 

-> Result<String, Error>  
{
 
    // =================================
    // FIXME: replace this part with `ModelConnection`
    let connection = Connection::session().await?;

    let proxy = Model1Proxy::new(&connection).await?;
    let model = Model1Struct{proxy};
    // =================================

    let _data = IrisData{col1:sepal_length, col2:sepal_width ,col3:petal_length ,col4:petal_width};
    let serialized = serde_json::to_string(&_data).unwrap();

    let reply = model.test(serialized.to_string()).await;
    reply
    
}
```

**Comment by sseoreo** [comment]
Please see PR #24
